steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/asteroids-neon:$COMMIT_SHA', '.']
  
  # Subir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/asteroids-neon:$COMMIT_SHA']
  
  # Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'asteroids-neon'
      - '--image'
      - 'gcr.io/$PROJECT_ID/asteroids-neon:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/asteroids-neon:$COMMIT_SHA'